spring:
  config:
    activate:
      on-profile: develop

  r2dbc:
    url: r2dbc:h2:mem:///test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
    initialization-mode: always
    port: 9094

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG

msa:
  client-url:
    member: http://localhost:8081 # 회원 서비스 주소
