
spring:
  profiles:
    active: develop

  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  port: 8081
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      show-details: always # Actuator에서 자세한 정보들을 확인하기 위해 설정

jwt:
  secretKey: # jwt 시크릿키
    accessToken: YWNjZXNzVG9rZW5TZWNyZXRLZXlGb3JBc3NpZ25tZW50
    refreshToken: cmVmcmVzaFRva2VuU2VjcmV0S2V5Rm9yQXNzaWdubWVudA==
