# 부동산 중개 플랫폼 API Test

### 회원 가입
POST http://localhost:8080/auth/member-register
Content-Type: application/json
Accept: application/json

{
  "memberType": "LESSOR",
  "memberLoginId": "test@gmail.com",
  "memberPassword": "password123",
  "memberName": "다방이",
  "memberBirth": "1991-01-01",
  "memberPhone": "01012341234"
}

> {% // response handler
client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
    client.global.set("memberToken", response.body.memberToken);
    client.log("memberToken >>> " + client.global.get("memberToken"));
    client.global.set("accessToken", response.body.accessToken);
    client.log("accessToken >>> " + client.global.get("accessToken"));
    client.global.set("refreshToken", response.body.refreshToken);
    client.log("refreshToken >>> " + client.global.get("refreshToken"));
});
%}

### 내방 등록
// 회원 가입 API를 통해 얻은 {accessToken} 사용
POST http://localhost:8080/house/register
Content-Type: application/json
Accept: application/json
Authorization: {{accessToken}}

{
  "memberToken": "492bc213-5c47-422f-9390-1b0c2206bcbe",
  "houseAddress": "방 주소",
  "houseType": "ONE",
  "rentalList": [
    {
      "rentalType": "JEONSE",
      "deposit": 5000,
      "rent": 0
    },
    {
      "rentalType": "MONTHLY",
      "deposit": 1000,
      "rent": 50
    }
  ]
}

> {% // response handler
client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
    client.global.set("houseToken", response.body.houseToken);
    client.log("houseToken >>> " + client.global.get("houseToken"));
});
%}

### 내방 수정
// 회원 가입 API를 통해 얻은 {accessToken} 사용
PUT http://localhost:8080/house/modify
Content-Type: application/json
Accept: application/json
Authorization: {{accessToken}}

{
  "houseToken": "4ff3f414-7a5e-4ce1-8234-76788b5eff87",
  "houseAddress": "방 주소",
  "houseType": "ONE",
  "rentalList": [
    {
      "rentalToken": "8143d59c-2e61-4157-8380-9da06713c847",
      "rentalType": "JEONSE",
      "deposit": 5000,
      "rent": 0
    },
    {
      "rentalToken": null,
      "rentalType": "MONTHLY",
      "deposit": 1000,
      "rent": 50
    }
  ]
}

### 내방 삭제
// 내방 등록 API를 통해 얻은 {houseToken} 사용
// 회원 가입 API를 통해 얻은 {accessToken} 사용
DELETE http://localhost:8080/house/delete/{{houseToken}}
Content-Type: application/json
Accept: application/json
Authorization: {{accessToken}}

### 내방 정보 조회
// 회원 가입 API를 통해 얻은 {accessToken} 사용
GET http://localhost:8080/house/info/4ff3f414-7a5e-4ce1-8234-76788b5eff81
Accept: application/json
Authorization: {{accessToken}}
