
spring:
  profiles:
    active: develop

  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  port: 8082
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      show-details: always # Actuator에서 자세한 정보들을 확인하기 위해 설정

